package rmiclient.frames;

import java.rmi.RemoteException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import rmicore.Service;

public class ConsultNewsDateFrame extends javax.swing.JFrame {

    private final Service rm;
    
    public ConsultNewsDateFrame(Service rm) {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.rm = rm;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l_titulo = new javax.swing.JLabel();
        l_data_inicial = new javax.swing.JLabel();
        l_data_final = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_noticia = new javax.swing.JTextArea();
        bt_consultar = new javax.swing.JButton();
        tf_data_inicial = new javax.swing.JTextField();
        tf_data_final = new javax.swing.JTextField();
        l_topico = new javax.swing.JLabel();
        tf_topico = new javax.swing.JTextField();
        bt_menu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Consulta de notícias");

        l_titulo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        l_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_titulo.setText("Consulta de Noticia");

        l_data_inicial.setText("Data Inicial:");

        l_data_final.setText("Data Final:");

        ta_noticia.setEditable(false);
        ta_noticia.setColumns(20);
        ta_noticia.setRows(5);
        jScrollPane1.setViewportView(ta_noticia);

        bt_consultar.setText("Consultar");
        bt_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_consultarActionPerformed(evt);
            }
        });

        tf_data_inicial.setToolTipText("");
        tf_data_inicial.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        l_topico.setText("Tópico:");

        bt_menu.setText("Voltar ao Menu Inicial");
        bt_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_menuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(l_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(bt_consultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_menu, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(l_data_inicial)
                        .addGap(18, 18, 18)
                        .addComponent(tf_data_inicial, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(l_data_final)
                        .addGap(23, 23, 23)
                        .addComponent(tf_data_final, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(l_topico)
                        .addGap(40, 40, 40)
                        .addComponent(tf_topico, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(l_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_topico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(l_topico))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l_data_inicial)
                            .addComponent(tf_data_inicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(l_data_final)
                            .addComponent(tf_data_final, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addComponent(bt_consultar)
                        .addGap(18, 18, 18)
                        .addComponent(bt_menu))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_consultarActionPerformed

        ta_noticia.setText("");
        if(!isValidParameters(tf_topico.getText(), tf_data_inicial.getText(), tf_data_final.getText())){
            return;
        }                
        try {
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");        
            LocalDate dateInitial = LocalDate.parse(tf_data_inicial.getText(), formatter);
            LocalDate dateEnd = LocalDate.parse(tf_data_final.getText(), formatter);                           
            try {
                ArrayList<String> news = rm.consultNewsByDate(tf_topico.getText(), dateInitial, dateEnd);
                if(news.isEmpty()){
                    JOptionPane.showMessageDialog(null, "Nenhuma notícia encontrada para estes filtros!");
                } else {
                    news.forEach((s) -> {
                        ta_noticia.append(s);
                    });                                
                }
            } catch (RemoteException ex) {
                JOptionPane.showMessageDialog(null, "Erro ao consultar notícias: " + ex.getMessage());
            }
        } catch (Exception e){
            JOptionPane.showMessageDialog(null, "Data inválida: " + e.getMessage());
        }
    }//GEN-LAST:event_bt_consultarActionPerformed

    private boolean isValidParameters(String topic, String dataInicial, String dataFinal){
        if(topic.isEmpty()){
            JOptionPane.showMessageDialog(null, "Nome do tópico é obrigatório!");
            return false;
        }
        if(dataInicial.isEmpty()){
            JOptionPane.showMessageDialog(null, "Data inicial é obrigatória!");
            return false;
        }
        if(dataFinal.isEmpty()){
            JOptionPane.showMessageDialog(null, "Data final é obrigatória!");
            return false;
        }
        return true;
    }
    
    private void bt_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_menuActionPerformed
        this.dispose();
    }//GEN-LAST:event_bt_menuActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_consultar;
    private javax.swing.JButton bt_menu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel l_data_final;
    private javax.swing.JLabel l_data_inicial;
    private javax.swing.JLabel l_titulo;
    private javax.swing.JLabel l_topico;
    private javax.swing.JTextArea ta_noticia;
    private javax.swing.JTextField tf_data_final;
    private javax.swing.JTextField tf_data_inicial;
    private javax.swing.JTextField tf_topico;
    // End of variables declaration//GEN-END:variables
}
