package rmiclient.frames;

import java.net.InetAddress;
import java.net.UnknownHostException;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.rmi.server.UnicastRemoteObject;
import javax.swing.JOptionPane;
import rmiclient.server.ServiceClient;
import rmiclient.server.ServiceClientImplement;
import rmicore.Service;
import rmicore.domain.User;

public class HomeSubscriberFrame extends javax.swing.JFrame {

    private final Service rm;
    private final User user;
    
    public HomeSubscriberFrame(Service rm, User user) throws RemoteException, UnknownHostException {
        initComponents();
        setLocationRelativeTo(null);
        this.rm = rm;
        this.user = user;        
        createConnectionServer();
    }
    
    private void createConnectionServer() throws RemoteException, UnknownHostException {        
        String ip = InetAddress.getLocalHost().getHostAddress();
        Registry registry = LocateRegistry.createRegistry(user.getPort());
        ServiceClientImplement srvCliImp = new ServiceClientImplement();
        ServiceClient serv = (ServiceClient) UnicastRemoteObject.exportObject(srvCliImp, 0);
        registry.rebind(ip + "/serviceclient", serv);
        System.out.println("Servidor do cliente no ar. Usuário: " + user.getUsername() + " Porta: " + user.getPort() + " IP: " + ip);
        user.setIp(ip);
        srvCliImp.setHomeSubscriberFrm(this);
    }
    
    public void appendNewsOnFeed(String news){
        ta_feedNews.append(news);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l_titulofeed = new javax.swing.JLabel();
        bt_inscrever = new javax.swing.JButton();
        bt_consutar = new javax.swing.JButton();
        bt_logoff = new javax.swing.JButton();
        bt_ultima = new javax.swing.JButton();
        l_titulo1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_feedNews = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home - Subscriber");

        l_titulofeed.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        l_titulofeed.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_titulofeed.setText("Feed de notícias");

        bt_inscrever.setText("Inscreve-se em Tópicos");
        bt_inscrever.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_inscreverActionPerformed(evt);
            }
        });

        bt_consutar.setText("Consultar Notícias");
        bt_consutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_consutarActionPerformed(evt);
            }
        });

        bt_logoff.setText("Sair");
        bt_logoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_logoffActionPerformed(evt);
            }
        });

        bt_ultima.setText("Última Notícia");
        bt_ultima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ultimaActionPerformed(evt);
            }
        });

        l_titulo1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        l_titulo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l_titulo1.setText("Bem Vindo!");

        ta_feedNews.setEditable(false);
        ta_feedNews.setColumns(20);
        ta_feedNews.setRows(5);
        jScrollPane1.setViewportView(ta_feedNews);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bt_inscrever, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                    .addComponent(bt_consutar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_ultima, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(l_titulofeed, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_logoff, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(l_titulo1, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(bt_inscrever)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_consutar)
                .addGap(11, 11, 11)
                .addComponent(bt_ultima)
                .addGap(18, 18, 18)
                .addComponent(l_titulofeed, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bt_logoff)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(l_titulo1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(433, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_inscreverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_inscreverActionPerformed
        try {
            RegisterTopicsFrame top = new RegisterTopicsFrame(rm, user);
            top.setVisible(true);
        } catch (RemoteException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao se inscrever no tópico: " + ex.getMessage());
        }
    }//GEN-LAST:event_bt_inscreverActionPerformed

    private void bt_consutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_consutarActionPerformed
        ConsultNewsDateFrame con = new ConsultNewsDateFrame(rm);
        con.setVisible(true);
    }//GEN-LAST:event_bt_consutarActionPerformed

    private void bt_ultimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ultimaActionPerformed
        LastNewsFrame not = new LastNewsFrame(rm);
        not.setVisible(true);
    }//GEN-LAST:event_bt_ultimaActionPerformed

    private void bt_logoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_logoffActionPerformed
        user.setPort(0);
        user.setIp(null);
        this.dispose();
    }//GEN-LAST:event_bt_logoffActionPerformed

 
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_consutar;
    private javax.swing.JButton bt_inscrever;
    private javax.swing.JButton bt_logoff;
    private javax.swing.JButton bt_ultima;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel l_titulo1;
    private javax.swing.JLabel l_titulofeed;
    private javax.swing.JTextArea ta_feedNews;
    // End of variables declaration//GEN-END:variables
}
