package rmiclient.frames;

import java.rmi.RemoteException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import rmicore.Service;
import rmicore.domain.User;

public class HomePublisherFrame extends javax.swing.JFrame {

    private static Service rm;
    private static User user;
    
    public HomePublisherFrame(Service rm, User user) {
        initComponents();
        setLocationRelativeTo(null);
        this.rm = rm;
        this.user = user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bt_addTopico = new javax.swing.JButton();
        bt_ConsultarTopico = new javax.swing.JButton();
        bt_InserirNoticia = new javax.swing.JButton();
        bt_ConsultarNoticiasPublicadas = new javax.swing.JButton();
        bt_logoff = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home - Publisher");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bem Vindo!");

        bt_addTopico.setText("Adicionar tópico");
        bt_addTopico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_addTopicoActionPerformed(evt);
            }
        });

        bt_ConsultarTopico.setText("Consultar tópicos existentes");
        bt_ConsultarTopico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ConsultarTopicoActionPerformed(evt);
            }
        });

        bt_InserirNoticia.setText("Inserir noticia em um tópico");
        bt_InserirNoticia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_InserirNoticiaActionPerformed(evt);
            }
        });

        bt_ConsultarNoticiasPublicadas.setText("Consultar notícias publicadas");
        bt_ConsultarNoticiasPublicadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ConsultarNoticiasPublicadasActionPerformed(evt);
            }
        });

        bt_logoff.setText("Sair");
        bt_logoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_logoffActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(bt_logoff, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                    .addComponent(bt_ConsultarNoticiasPublicadas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                    .addComponent(bt_InserirNoticia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_ConsultarTopico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_addTopico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_addTopico)
                .addGap(18, 18, 18)
                .addComponent(bt_ConsultarTopico)
                .addGap(18, 18, 18)
                .addComponent(bt_InserirNoticia)
                .addGap(18, 18, 18)
                .addComponent(bt_ConsultarNoticiasPublicadas)
                .addGap(18, 18, 18)
                .addComponent(bt_logoff)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_addTopicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_addTopicoActionPerformed
       AddTopicFrame atf = new AddTopicFrame(rm,user);
       atf.setVisible(true);
    }//GEN-LAST:event_bt_addTopicoActionPerformed

    private void bt_InserirNoticiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_InserirNoticiaActionPerformed
       InsertNewsFrame inf = new InsertNewsFrame(rm, user);
       inf.setVisible(true);
    }//GEN-LAST:event_bt_InserirNoticiaActionPerformed

    private void bt_ConsultarNoticiasPublicadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ConsultarNoticiasPublicadasActionPerformed
       ConsultPublicationsFrame cpf = new ConsultPublicationsFrame(rm, user);
       cpf.setVisible(true);
    }//GEN-LAST:event_bt_ConsultarNoticiasPublicadasActionPerformed

    private void bt_ConsultarTopicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ConsultarTopicoActionPerformed
        try {
            ArrayList<String> topics = rm.consultTopicExistings();
            if(topics.isEmpty()){
                JOptionPane.showMessageDialog(null, "Não existem tópicos a serem consultados!");
            } else {
                ConsultTopicsFrame consultTopicsFrm = new ConsultTopicsFrame(topics);
                consultTopicsFrm.setVisible(true);
            }
        } catch (RemoteException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao consultar tópicos: " + ex.getMessage());
        }
    }//GEN-LAST:event_bt_ConsultarTopicoActionPerformed

    private void bt_logoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_logoffActionPerformed
        this.dispose();
    }//GEN-LAST:event_bt_logoffActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_ConsultarNoticiasPublicadas;
    private javax.swing.JButton bt_ConsultarTopico;
    private javax.swing.JButton bt_InserirNoticia;
    private javax.swing.JButton bt_addTopico;
    private javax.swing.JButton bt_logoff;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
