package rmiclient.frames;

import java.rmi.RemoteException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import rmicore.Service;
import rmicore.domain.User;

public class RegisterTopicsFrame extends javax.swing.JFrame {

    private final Service rm;
    private final User user;
    
    public RegisterTopicsFrame(Service rm, User user) throws RemoteException {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.rm = rm;
        this.user = user;
        loadTopics();
    }
    
    private void loadTopics() throws RemoteException {
        ArrayList<String> topics = rm.consultTopicExistings();        
        topics.forEach((s) -> {
            ta_topicos.append(s + "\n");
        });        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        L_title = new javax.swing.JLabel();
        bt_inscrever = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_topicos = new javax.swing.JTextArea();
        l_digite = new javax.swing.JLabel();
        tf_topico = new javax.swing.JTextField();
        bt_menu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Insrição em tópicos");

        L_title.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        L_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L_title.setText("Inscrever-se");

        bt_inscrever.setText("Inscrever");
        bt_inscrever.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_inscreverActionPerformed(evt);
            }
        });

        ta_topicos.setEditable(false);
        ta_topicos.setColumns(20);
        ta_topicos.setRows(5);
        jScrollPane1.setViewportView(ta_topicos);

        l_digite.setText("Digite o tópico:");

        bt_menu.setText("Voltar ao Menu Inicial");
        bt_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_menuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(L_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(l_digite)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_topico, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(bt_inscrever, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bt_menu))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(L_title, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_topico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_digite))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_inscrever)
                    .addComponent(bt_menu))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @SuppressWarnings("null")
    private void bt_inscreverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_inscreverActionPerformed
        try {
            if(tf_topico.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Informe o tópico!");
            } else {
               if(rm.subscribeOnTopic(user, tf_topico.getText()) == true){
                   JOptionPane.showMessageDialog(null, "Incrição realizada com sucesso!");
                   tf_topico.setText("");
               } else {
                   JOptionPane.showMessageDialog(rootPane, "Não foi possivel se inscrever no tópico!","ERRO", JOptionPane.ERROR_MESSAGE);
               }
            }    
        } catch (RemoteException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao se inscrever no tópico: " + ex.getMessage(),"ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_bt_inscreverActionPerformed

    private void bt_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_menuActionPerformed
        this.dispose();        
    }//GEN-LAST:event_bt_menuActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L_title;
    private javax.swing.JButton bt_inscrever;
    private javax.swing.JButton bt_menu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel l_digite;
    private javax.swing.JTextArea ta_topicos;
    private javax.swing.JTextField tf_topico;
    // End of variables declaration//GEN-END:variables
}
